"""Build a run directory. Never overwrites an existing one."""
import json
import shutil
import subprocess
from datetime import datetime
from pathlib import Path

from . import namelist
from .paths import SITE

REPO = Path(__file__).resolve().parents[1]
CASE_FILES = REPO / 'case'
OUT_DIRS = ('OUT_2D', 'OUT_3D', 'OUT_MOMENTS', 'OUT_MOVIES', 'OUT_STAT', 'RESTART')


def git_hash():
    try:
        return subprocess.run(['git', '-C', str(REPO), 'rev-parse', '--short', 'HEAD'],
                              capture_output=True, text=True).stdout.strip() or 'unknown'
    except OSError:
        return 'unknown'


def stage_run(run_dir, params, snd_path, *, allow_diurnal=False, site=SITE, meta=None,
              link_exe=True, grid='grd'):
    """Create run_dir with: OUT_*/RESTART, exe symlink, CaseName, <case>/{prm,snd,grd},
    RUNDATA and radiation *.nc files, and config.json (every setting, for reproducibility)."""
    run_dir = Path(run_dir)
    if run_dir.exists():
        raise FileExistsError(f'{run_dir} exists; nothing was changed.')
    case = site.case
    run_dir.mkdir(parents=True)
    for d in OUT_DIRS:
        (run_dir / d).mkdir()
    (run_dir / 'CaseName').write_text(f'{case}\n')
    case_dir = run_dir / case
    case_dir.mkdir()
    shutil.copy(CASE_FILES / case / grid, case_dir / 'grd')      # SAM always reads <case>/grd
    shutil.copy(snd_path, case_dir / 'snd')
    namelist.write_prm(case_dir / 'prm', params, allow_diurnal=allow_diurnal,
                       header=f'Generated by samheat {git_hash()} on {datetime.now():%Y-%m-%d %H:%M}. '
                              'Do not edit by hand.')
    if link_exe:
        exe = Path(site.build) / site.executable
        if not exe.exists():
            raise FileNotFoundError(f'executable not found: {exe}')
        (run_dir / site.executable).symlink_to(exe)
        src = Path(site.rundata_source)
        if (src / 'RUNDATA').exists():
            shutil.copytree(src / 'RUNDATA', run_dir / 'RUNDATA')
        for f in src.iterdir():
            if f.is_file() and f.suffix == '.nc':
                shutil.copy(f, run_dir / f.name)
    (run_dir / 'config.json').write_text(json.dumps(dict(
        created=datetime.now().isoformat(timespec='seconds'), samheat_git=git_hash(),
        snd_source=str(snd_path), grid=grid, prm=params, **(meta or {})), indent=2, default=str))
    return case_dir / 'prm'


def update_prm(run_dir, changes, allow_diurnal=False, site=SITE):
    """Change keys of an existing run's prm (e.g. nrestart, nstop) through the strict writer."""
    prm = Path(run_dir) / site.case / 'prm'
    params = namelist.merge(namelist.read_prm(prm), changes)
    namelist.write_prm(prm, params, allow_diurnal=allow_diurnal,
                       header=f'Generated by samheat {git_hash()}; updated {datetime.now():%Y-%m-%d %H:%M} '
                              f'with {changes}')
    return params
